"""add is_completed to watch_progress

Revision ID: 1156acb45995
Revises: ab00d9c91aef
Create Date: 2026-06-22 13:35:59.150280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1156acb45995'
down_revision: Union[str, Sequence[str], None] = 'ab00d9c91aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'is_completed')
    # ### end Alembic commands ###
