"""add movie status, hls_file path and make duration nullable

Revision ID: 6f272b996f8a
Revises: 1156acb45995
Create Date: 2026-06-23 11:10:17.077387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f272b996f8a"
down_revision: Union[str, Sequence[str], None] = "1156acb45995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "duration_seconds",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "movies",
        sa.Column(
            "status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
    )
    op.add_column("movies", sa.Column("hls_playlist_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "hls_playlist_path")
    op.drop_column("movies", "status")
    op.drop_column("movies", "duration_seconds")
    # ### end Alembic commands ###
