"""add movie metadata fields

Revision ID: 9bb40ef5dca5
Revises: 9e14adec48fd
Create Date: 2026-07-09 12:27:58.623728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb40ef5dca5'
down_revision: Union[str, Sequence[str], None] = '9e14adec48fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movies', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('genres', sa.JSON(), nullable=True))
    op.add_column('movies', sa.Column('age_rating', sa.String(length=20), nullable=True))
    op.add_column('movies', sa.Column('director', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('cast', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'cast')
    op.drop_column('movies', 'director')
    op.drop_column('movies', 'age_rating')
    op.drop_column('movies', 'genres')
    op.drop_column('movies', 'language')
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
