"""add watch history fields

Revision ID: 9e14adec48fd
Revises: 6f272b996f8a
Create Date: 2026-07-06 21:31:06.979001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e14adec48fd'
down_revision: Union[str, Sequence[str], None] = '6f272b996f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('watch_progress', sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('watch_progress', sa.Column('total_watch_time_seconds', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'total_watch_time_seconds')
    op.drop_column('watch_progress', 'last_watched_at')
    op.drop_column('watch_progress', 'started_at')
    # ### end Alembic commands ###
