"""add poster filename

Revision ID: a87cb0ff5adc
Revises: cea6ee858444
Create Date: 2026-06-19 10:38:17.006519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a87cb0ff5adc"
down_revision: Union[str, Sequence[str], None] = "cea6ee858444"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies", sa.Column("poster_filename", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "poster_filename")
    # ### end Alembic commands ###
