services:

  postgres:
    image: postgres:17
    container_name: ott-postgres

    environment:
      POSTGRES_DB: ott
      POSTGRES_USER: ott
      POSTGRES_PASSWORD: ott

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api

    container_name: ott-api

    ports:
      - "8100:8100"

    depends_on:
      - postgres

    volumes:
      - ./api:/app
      - ./media:/media

    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8100"
      - --reload

  streamer:
    build:
      context: ./streamer

    container_name: ott-streamer

    ports:
      - "8180:8180"

    volumes:
      - ./media:/media
      - ./streamer:/app
    
    environment:
      - SECRET_KEY=super-secret-key-change-later

    command: air

  frontend:
    build:
      context: ./frontend

    container_name: ott-frontend

    ports:
      - "3000:80"
    
    volumes:
      - ./frontend:/usr/share/nginx/html

  # transcoder:
  #   build:
  #     context: ./transcoder
    
  #   container_name: ott-transcoder

  #   depends_on:
  #     - postgres

  #   volumes:
  #     - ./media:/media
  #     - ./transcoder:/app
    
  #   environment:
  #     - DATABASE_URL=postgres://ott:ott@postgres:5432/ott?sslmode=disable
    
  #   command: air

volumes:
  postgres_data: